### PR TITLE
fix(banner): renamed linkHref to href

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
Renamed linkHref to href.

**Solving issue**  
Fixes: -

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Link -> Web Components

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

### CODE REVIEW

**Review by timrombergjakobsson — COMMENTED** [review]
The appearance is slightly different from Chrome to Safar, see below screenshots:

**Chrome**
Skärmavbild 2023-02-16 kl  09 36 44

**Safari**
Skärmavbild 2023-02-16 kl  09 38 53

Note that in dark mode they look the same.

**Comment by mJarsater** [comment]
> The appearance is slightly different from Chrome to Safar, see below screenshots:
> 
> **Chrome** Skärmavbild 2023-02-16 kl 09 36 44
> 
> **Safari** Skärmavbild 2023-02-16 kl 09 38 53
> 
> Note that in dark mode they look the same.

Hmm.. can't see the issue on my side. Are you on safari v14? Also, could you check to see that the link i chrome is not visited? The visited has some different styling 🖌️

**Comment by timrombergjakobsson** [comment]
> https://deploy-preview-836--tegel-storybook.netlify.app



> > The appearance is slightly different from Chrome to Safar, see below screenshots:
> > **Chrome** Skärmavbild 2023-02-16 kl 09 36 44
> > **Safari** Skärmavbild 2023-02-16 kl 09 38 53
> > Note that in dark mode they look the same.
> 
> Hmm.. can't see the issue on my side. Are you on safari v14? Also, could you check to see that the link i chrome is not visited? The visited has some different styling 🖌️

Yep, same Safari as before, and it is the visited state that does not have the black apperance.

**Comment by mJarsater** [comment]
> > https://deploy-preview-836--tegel-storybook.netlify.app
> 
> > > The appearance is slightly different from Chrome to Safar, see below screenshots:
> > > **Chrome** Skärmavbild 2023-02-16 kl 09 36 44
> > > **Safari** Skärmavbild 2023-02-16 kl 09 38 53
> > > Note that in dark mode they look the same.
> > 
> > 
> > Hmm.. can't see the issue on my side. Are you on safari v14? Also, could you check to see that the link i chrome is not visited? The visited has some different styling 🖌️
> 
> Yep, same Safari as before, and it is the visited state that does not have the black apperance.

Great, thanks! Looks like this might be a safari thing.. https://macreports.com/safari-visited-links-not-changing-color-fix/#:~:text=Usually%2C%20for%20%E2%80%9Cvisited%E2%80%9D%20links,that%20have%20been%20visited%20already.

I'll look into it

**Comment by mJarsater** [comment]
> > https://deploy-preview-836--tegel-storybook.netlify.app
> 
> > > The appearance is slightly different from Chrome to Safar, see below screenshots:
> > > **Chrome** Skärmavbild 2023-02-16 kl 09 36 44
> > > **Safari** Skärmavbild 2023-02-16 kl 09 38 53
> > > Note that in dark mode they look the same.
> > 
> > 
> > Hmm.. can't see the issue on my side. Are you on safari v14? Also, could you check to see that the link i chrome is not visited? The visited has some different styling 🖌️
> 
> Yep, same Safari as before, and it is the visited state that does not have the black apperance.

Great, thanks! Looks like this might be a safari thing.. https://macreports.com/safari-visited-links-not-changing-color-fix/#:~:text=Usually%2C%20for%20%E2%80%9Cvisited%E2%80%9D%20links,that%20have%20been%20visited%20already.

I'll look into it

**Comment by mJarsater** [comment]
> > > https://deploy-preview-836--tegel-storybook.netlify.app
> > 
> > 
> > > > The appearance is slightly different from Chrome to Safar, see below screenshots:
> > > > **Chrome** Skärmavbild 2023-02-16 kl 09 36 44
> > > > **Safari** Skärmavbild 2023-02-16 kl 09 38 53
> > > > Note that in dark mode they look the same.
> > > 
> > > 
> > > Hmm.. can't see the issue on my side. Are you on safari v14? Also, could you check to see that the link i chrome is not visited? The visited has some different styling 🖌️
> > 
> > 
> > Yep, same Safari as before, and it is the visited state that does not have the black apperance.
> 
> Great, thanks! Looks like this might be a safari thing.. https://macreports.com/safari-visited-links-not-changing-color-fix/#:~:text=Usually%2C%20for%20%E2%80%9Cvisited%E2%80%9D%20links,that%20have%20been%20visited%20already.
> 
> I'll look into it

Alright, seems to be an issue with how safari displays links when href="#". Changed it to www.scania.com locally and everything worked fine. Not sure I want to change it to that in storybook though.

**Comment by timrombergjakobsson** [comment]
> > > > https://deploy-preview-836--tegel-storybook.netlify.app
> > > 
> > > 
> > > > > The appearance is slightly different from Chrome to Safar, see below screenshots:
> > > > > **Chrome** Skärmavbild 2023-02-16 kl 09 36 44
> > > > > **Safari** Skärmavbild 2023-02-16 kl 09 38 53
> > > > > Note that in dark mode they look the same.
> > > > 
> > > > 
> > > > Hmm.. can't see the issue on my side. Are you on safari v14? Also, could you check to see that the link i chrome is not visited? The visited has some different styling 🖌️
> > > 
> > > 
> > > Yep, same Safari as before, and it is the visited state that does not have the black apperance.
> > 
> > 
> > Great, thanks! Looks like this might be a safari thing.. https://macreports.com/safari-visited-links-not-changing-color-fix/#:~:text=Usually%2C%20for%20%E2%80%9Cvisited%E2%80%9D%20links,that%20have%20been%20visited%20already.
> > I'll look into it
> 
> Alright, seems to be an issue with how safari displays links when href="#". Changed it to [www.scania.com](http://www.scania.com) locally and everything worked fine. Not sure I want to change it to that in storybook though.

Great find! No, does not sound like something worth changing for just that.

**Review by timrombergjakobsson — APPROVED** [review]

**Pull request merged**
