### PR TITLE
fix: removing missing files import

### PR DESCRIPTION
**Pull request by theJohnnyMe**
**Describe pull-request**  
Removing imports that cause build to fail

**Solving issue**  
The import that are removed were anyway missing files that were causing build-in theme-light to fail.

**How to test**  
1. On main brunch, do npm run clean and then try to run npm i - it will fail
2. Do the same for this branch - it should pass.

### CODE REVIEW

**Review by gaonita — APPROVED** [review]
nice clean up ✨  still getting EBUSY error in both branches but once you delete the dist file it works as usual.

**Comment by areblk** [comment]
I tried this out and as usual, `npm i` freezes when building @scania/icons (both in main and in this branch). After aborting and re-running `npm i` i get messages that there is problem trying to create css files and some other errors until build finally fails.

**Comment by areblk** [comment]
When I remove all my changes and run `npm run clean` and `npm i` it fails.

Complete log

```bash
AREBLK@RD0080095 MINGW64 /c/dev/sdds (missing_files)
$ npm run clean

> sdds@1.1.0 clean
> lerna clean     

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Removing the following directories:     
lerna info clean components\node_modules
lerna info clean theme\core\colour\node_modules    
lerna info clean theme\core\grid\node_modules      
lerna info clean theme\core\icons\node_modules     
lerna info clean theme\core\node_modules
lerna info clean theme\core\typography\node_modules
lerna info clean theme\light\node_modules
? Proceed? Yes
lerna info clean removing C:\dev\sdds\components\node_modules
lerna info clean removing C:\dev\sdds\theme\core\colour\node_modules
lerna info clean removing C:\dev\sdds\theme\core\grid\node_modules
lerna info clean removing C:\dev\sdds\theme\core\icons\node_modules     
lerna info clean removing C:\dev\sdds\theme\core\node_modules
lerna info clean removing C:\dev\sdds\theme\core\typography\node_modules
lerna info clean removing C:\dev\sdds\theme\light\node_modules
lerna success clean finished

AREBLK@RD0080095 MINGW64 /c/dev/sdds (missing_files)
$ npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

> sdds@1.1.0 install
> lerna bootstrap

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 7 packages

> sdds@1.1.0 prepare
> husky install && npm run build

husky - Git hooks installed

> sdds@1.1.0 build
> lerna run build

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 6 packages: "npm run build"
lerna info run Ran npm script 'build' in '@scania/colour' in 2.8s:

> @scania/colour@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _colour.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/grid' in 3.0s:

> @scania/grid@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _grid.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/typography' in 3.3s:

> @scania/typography@1.2.1 build
> node compile.js

removing dist...
creating folders...
file: _mixins.scss
file: _selectors.scss
file: _tokens.scss
file: _typography.scss
file: _vars.scss
file: typography-vars.scss
dist/ folder contains all files
Import base-unit
Import prefix
lerna info run Ran npm script 'build' in '@scania/icons' in 8.8s:

> @scania/icons@1.1.1 build
> gulp

[09:36:28] Using gulpfile C:\dev\sdds\theme\core\icons\gulpfile.js
[09:36:28] Starting 'default'...
[09:36:28] Starting 'clean'...
[09:36:28] Finished 'clean' after 54 ms
[09:36:28] Starting 'initFolders'...
[09:36:28] Finished 'initFolders' after 2.35 ms
[09:36:28] Starting 'build'...
[09:36:30] Finished 'build' after 2.23 s
[09:36:30] Starting 'createIconfont'...
[09:36:31] gulp-svgicons2svgfont: The provided icons do not have the same heights. This could lead to unexpected results. Using the normalize option may help.  
[09:36:31] gulp-svgicons2svgfont: A fontHeight of at least than 1000 is recommended, otherwise further steps (rounding in svg2ttf) could lead to ugly results. Use the fontHeight option to scale icons.
[09:36:31] gulp-svgicons2svgfont: Font created
[09:36:32] Finished 'createIconfont' after 1.7 s
[09:36:32] Starting 'cleanTemp'...
[09:36:32] Finished 'cleanTemp' after 40 ms
[09:36:32] Finished 'default' after 4.03 s

AREBLK@RD0080095 MINGW64 /c/dev/sdds (missing_files)
$ npm i

> sdds@1.1.0 install
> lerna bootstrap

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 7 packages

> sdds@1.1.0 prepare
> husky install && npm run build

husky - Git hooks installed

> sdds@1.1.0 build
> lerna run build

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 6 packages: "npm run build"
lerna info run Ran npm script 'build' in '@scania/colour' in 2.5s:

> @scania/colour@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _colour.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/grid' in 2.8s:

> @scania/grid@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _grid.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/typography' in 3.2s:

> @scania/typography@1.2.1 build
> node compile.js

removing dist...
creating folders...
file: _mixins.scss
file: _selectors.scss
file: _tokens.scss
file: _typography.scss
file: _vars.scss
file: typography-vars.scss
dist/ folder contains all files
Import base-unit
Import prefix
lerna info run Ran npm script 'build' in '@scania/icons' in 7.8s:

> @scania/icons@1.1.1 build
> gulp

[09:37:54] Using gulpfile C:\dev\sdds\theme\core\icons\gulpfile.js
[09:37:54] Starting 'default'...
[09:37:54] Starting 'clean'...
[09:37:54] Finished 'clean' after 47 ms
[09:37:54] Starting 'initFolders'...
[09:37:54] Finished 'initFolders' after 1.88 ms
[09:37:54] Starting 'build'...
[09:37:56] Finished 'build' after 1.94 s
[09:37:56] Starting 'createIconfont'...
[09:37:57] gulp-svgicons2svgfont: The provided icons do not have the same heights. This could lead to unexpected results. Using the normalize option may help.  
[09:37:57] gulp-svgicons2svgfont: A fontHeight of at least than 1000 is recommended, otherwise further steps (rounding in svg2ttf) could lead to ugly results. Use the fontHeight option to scale icons.
[09:37:57] gulp-svgicons2svgfont: Font created
[09:37:58] Finished 'createIconfont' after 1.92 s
[09:37:58] Starting 'cleanTemp'...
[09:37:58] Finished 'cleanTemp' after 38 ms
[09:37:58] Finished 'default' after 3.95 s
lerna info run Ran npm script 'build' in '@scania/theme-light' in 10.0s:

> @scania/theme-light@4.2.1 build
> gulp build

[09:37:54] Requiring external module @babel/register
[09:37:58] Using gulpfile C:\dev\sdds\theme\light\gulpfile.babel.js
[09:37:58] Starting 'build'...
[09:37:58] Starting 'checkEnvironment'...
[09:37:58] Finished 'checkEnvironment' after 1.09 ms
[09:37:58] Starting 'clean'...
[09:37:58] Finished 'clean' after 25 ms
[09:37:58] Starting 'initFolders'...
[09:37:58] Finished 'initFolders' after 1.7 ms
[09:37:58] Starting 'initImages'...
[09:37:58] Starting 'copyImages'...
[09:37:58] Finished 'copyImages' after 56 ms
[09:37:58] Starting 'generateImages'...
[09:38:00] Finished 'generateImages' after 1.52 s
[09:38:00] Finished 'initImages' after 1.58 s
[09:38:00] Starting 'initFavicons'...
Generate favicon module
[09:38:00] Finished 'initFavicons' after 303 ms
[09:38:00] Starting 'initTheme'...
Generate css variables for typography
Generate css variables for spacing
Generate css styles
dist/styles/c-card
dist/styles/c-content
dist/styles/c-cookie
Error: File to import not found or unreadable: ../components/list-group.        
    at Object.renderSync (C:\dev\sdds\theme\light\node_modules\node-sass\lib\index.js:440:23)
    at forEach (C:\dev\sdds\theme\light/gulpfile.babel.js:297:20)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds\theme\light\gulpfile.babel.js:18:103)    
    at _next (C:\dev\sdds\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds\theme\light\gulpfile.babel.js:20:364 {
  status: 1,
  file: 'stdin',
  line: 2,
  column: 1,
  formatted: 'Error: File to import not found or unreadable: ../components/list-group.\n' +
    '        on line 2 of stdin\n' +
    ">> @import '../components/list-group';\n" +
    '\n' +
    '   ^\n'
}
Problem in file src/old/patterns/c-cookie.scss or imports related to it

 ---- Problem in scss files, read error! ----

TypeError: Cannot read properties of undefined (reading 'css')
    at forEach (C:\dev\sdds\theme\light/gulpfile.babel.js:309:49)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds\theme\light\gulpfile.babel.js:18:103)    
    at _next (C:\dev\sdds\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds\theme\light\gulpfile.babel.js:20:364
    at new Promise (<anonymous>)

 ---- Problem trying create css files ----

dist/styles/c-modal
dist/styles/c-navigation
dist/styles/c-table
Error: File to import not found or unreadable: ../components/forms.
    at Object.renderSync (C:\dev\sdds\theme\light\node_modules\node-sass\lib\index.js:440:23)
    at forEach (C:\dev\sdds\theme\light/gulpfile.babel.js:297:20)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds\theme\light\gulpfile.babel.js:18:103)    
    at _next (C:\dev\sdds\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds\theme\light\gulpfile.babel.js:20:364 {
  status: 1,
  file: 'stdin',
  line: 4,
  column: 1,
  formatted: 'Error: File to import not found or unreadable: ../components/forms.\n' +
    '        on line 4 of stdin\n' +
    ">> @import '../components/forms';\n" +
    '\n' +
    '   ^\n'
}
Problem in file src/old/patterns/c-table.scss or imports related to it

 ---- Problem in scss files, read error! ----

TypeError: Cannot read properties of undefined (reading 'css')
    at forEach (C:\dev\sdds\theme\light/gulpfile.babel.js:309:49)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds\theme\light\gulpfile.babel.js:18:103)    
    at _next (C:\dev\sdds\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds\theme\light\gulpfile.babel.js:20:364
    at new Promise (<anonymous>)

 ---- Problem trying create css files ----

dist/styles/sdds-theme
Generate style module
Style updated.
[09:38:00] Finished 'initTheme' after 283 ms
[09:38:00] Starting 'copyScss'...
Copying scss... Output: dist/scss/
[09:38:01] Finished 'copyScss' after 102 ms
[09:38:01] Starting 'copyGlobalStyle'...
Copying corporate-ui-4 global style... output dist/styles/
[09:38:01] Finished 'copyGlobalStyle' after 9.57 ms
[09:38:01] Finished 'build' after 2.31 s
lerna ERR! npm run build exited 1 in '@scania/components'
lerna ERR! npm run build stdout:

> @scania/components@3.0.0 build
> npm run babel && npm run stencil --


> @scania/components@3.0.0 babel
> mkdirp .build && babel src/helpers/index.js --out-file .build/index.js        


> @scania/components@3.0.0 stencil
> stencil build --docs-json dist/data/docs.json

[38:04.9]  @stencil/core
[38:05.2]  v2.3.0
[38:05.5]  cache optimizations disabled
[38:08.9]  build, sdds-components, prod mode, started ...
[38:08.9]  transpile started ...
[38:14.1]  transpile finished in 5.21 s
[38:14.1]  copy started ...
[38:14.1]  generate custom elements bundle started ...
[38:14.1]  generate lazy started ...
[38:14.4]  copy finished (35 files) in 311 ms
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

[38:25.8]  generate custom elements bundle finished in 11.72 s
[38:37.7]  generate lazy finished in 23.62 s
[38:37.8]  updated readme docs: sdds-accordion
[38:37.8]  updated readme docs: sdds-accordion-item
[38:37.8]  updated readme docs: sdds-continousvalue-slider
[38:37.8]  updated readme docs: sdds-dropdown
[38:37.8]  updated readme docs: sdds-dropdown-filter
[38:37.8]  updated readme docs: sdds-dropdown-option
[38:37.8]  updated readme docs: sdds-dual-point-slider
[38:37.8]  updated readme docs: sdds-slider

[ ERROR ]  EBUSY: resource busy or locked, copyfile
           'C:\dev\sdds\components\src\helpers\core.js' ->
           'C:\dev\sdds\components\dist\core.js'

[38:37.8]  build failed in 28.91 s


lerna ERR! npm run build exited 1 in '@scania/components'
npm ERR! code 1
npm ERR! path C:\dev\sdds
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\areblk\AppData\Local\npm-cache\_logs\2022-03-25T08_37_36_020Z-debug-0.log

**Comment by areblk** [comment]
I cloned the repo to test if it worked due to old files. There is still problem creating css, but build doesn't fail. Complete log

```bash
AREBLK@RD0080095 MINGW64 /c/dev/sdds-1 (missing_files)
$ npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.        
npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> sdds@1.1.0 install
> lerna bootstrap

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 7 packages

> sdds@1.1.0 prepare
> husky install && npm run build

husky - Git hooks installed

> sdds@1.1.0 build
> lerna run build

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 6 packages: "npm run build"
lerna info run Ran npm script 'build' in '@scania/colour' in 2.7s:

> @scania/colour@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _colour.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/grid' in 2.9s:

> @scania/grid@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _grid.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/typography' in 3.3s:

> @scania/typography@1.2.1 build
> node compile.js

removing dist...
creating folders...
file: _mixins.scss
file: _selectors.scss
file: _tokens.scss
file: _typography.scss
file: _vars.scss
file: typography-vars.scss
dist/ folder contains all files
Import base-unit
Import prefix
lerna info run Ran npm script 'build' in '@scania/icons' in 8.3s:

> @scania/icons@1.1.1 build
> gulp

[09:49:53] Using gulpfile C:\dev\sdds-1\theme\core\icons\gulpfile.js
[09:49:53] Starting 'default'...
[09:49:53] Starting 'clean'...
[09:49:53] Finished 'clean' after 14 ms
[09:49:53] Starting 'initFolders'...
[09:49:53] Finished 'initFolders' after 2.05 ms
[09:49:53] Starting 'build'...
[09:49:55] Finished 'build' after 2.04 s
[09:49:55] Starting 'createIconfont'...
[09:49:56] gulp-svgicons2svgfont: The provided icons do not have the same heights. This could lead to unexpected results. Using the normalize option may help.  
[09:49:56] gulp-svgicons2svgfont: A fontHeight of at least than 1000 is recommended, otherwise further steps (rounding in svg2ttf) could lead to ugly results. Use the fontHeight option to scale icons.
[09:49:56] gulp-svgicons2svgfont: Font created
[09:49:57] Finished 'createIconfont' after 1.44 s
[09:49:57] Starting 'cleanTemp'...
[09:49:57] Finished 'cleanTemp' after 47 ms
[09:49:57] Finished 'default' after 3.55 s

AREBLK@RD0080095 MINGW64 /c/dev/sdds-1 (missing_files)
$ npm i

> sdds@1.1.0 install
> lerna bootstrap

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 7 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 7 packages

> sdds@1.1.0 prepare
> husky install && npm run build

husky - Git hooks installed

> sdds@1.1.0 build
> lerna run build

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 6 packages: "npm run build"
lerna info run Ran npm script 'build' in '@scania/colour' in 2.5s:

> @scania/colour@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _colour.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/grid' in 2.9s:

> @scania/grid@2.0.1 build
> node compile.js

removing dist...
creating folders...
file: _grid.scss
dist/ folder contains all files
lerna info run Ran npm script 'build' in '@scania/typography' in 3.3s:

> @scania/typography@1.2.1 build
> node compile.js

removing dist...
creating folders...
file: _mixins.scss
file: _selectors.scss
file: _tokens.scss
file: _typography.scss
file: _vars.scss
file: typography-vars.scss
dist/ folder contains all files
Import base-unit
Import prefix
lerna info run Ran npm script 'build' in '@scania/icons' in 7.9s:

> @scania/icons@1.1.1 build
> gulp

[09:50:58] Using gulpfile C:\dev\sdds-1\theme\core\icons\gulpfile.js
[09:50:58] Starting 'default'...
[09:50:58] Starting 'clean'...
[09:50:58] Finished 'clean' after 59 ms
[09:50:58] Starting 'initFolders'...
[09:50:58] Finished 'initFolders' after 1.79 ms
[09:50:58] Starting 'build'...
[09:51:00] Finished 'build' after 1.87 s
[09:51:00] Starting 'createIconfont'...
[09:51:01] gulp-svgicons2svgfont: The provided icons do not have the same heights. This could lead to unexpected results. Using the normalize option may help.  
[09:51:01] gulp-svgicons2svgfont: A fontHeight of at least than 1000 is recommended, otherwise further steps (rounding in svg2ttf) could lead to ugly results. Use the fontHeight option to scale icons.
[09:51:01] gulp-svgicons2svgfont: Font created
[09:51:02] Finished 'createIconfont' after 1.96 s
[09:51:02] Starting 'cleanTemp'...
[09:51:02] Finished 'cleanTemp' after 46 ms
[09:51:02] Finished 'default' after 3.94 s
lerna info run Ran npm script 'build' in '@scania/theme-light' in 9.9s:

> @scania/theme-light@4.2.1 build
> gulp build

[09:50:58] Requiring external module @babel/register
[09:51:03] Using gulpfile C:\dev\sdds-1\theme\light\gulpfile.babel.js
[09:51:03] Starting 'build'...
[09:51:03] Starting 'checkEnvironment'...
[09:51:03] Finished 'checkEnvironment' after 691 μs
[09:51:03] Starting 'clean'...
[09:51:03] Finished 'clean' after 19 ms
[09:51:03] Starting 'initFolders'...
[09:51:03] Finished 'initFolders' after 1.23 ms
[09:51:03] Starting 'initImages'...
[09:51:03] Starting 'copyImages'...
[09:51:03] Finished 'copyImages' after 43 ms
[09:51:03] Starting 'generateImages'...
[09:51:04] Finished 'generateImages' after 1.11 s
[09:51:04] Finished 'initImages' after 1.15 s
[09:51:04] Starting 'initFavicons'...
Generate favicon module
[09:51:04] Finished 'initFavicons' after 264 ms
[09:51:04] Starting 'initTheme'...
Generate css variables for typography
Generate css variables for spacing
Generate css styles
dist/styles/c-card
dist/styles/c-content
dist/styles/c-cookie
Error: File to import not found or unreadable: ../components/list-group.        
    at Object.renderSync (C:\dev\sdds-1\theme\light\node_modules\node-sass\lib\index.js:440:23)
    at forEach (C:\dev\sdds-1\theme\light/gulpfile.babel.js:297:20)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds-1\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds-1\theme\light\gulpfile.babel.js:18:103)  
    at _next (C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:364 {
  status: 1,
  file: 'stdin',
  line: 2,
  column: 1,
  formatted: 'Error: File to import not found or unreadable: ../components/list-group.\n' +
    '        on line 2 of stdin\n' +
    ">> @import '../components/list-group';\n" +
    '\n' +
    '   ^\n'
}
Problem in file src/old/patterns/c-cookie.scss or imports related to it

 ---- Problem in scss files, read error! ----

TypeError: Cannot read properties of undefined (reading 'css')
    at forEach (C:\dev\sdds-1\theme\light/gulpfile.babel.js:309:49)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds-1\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds-1\theme\light\gulpfile.babel.js:18:103)  
    at _next (C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:364
    at new Promise (<anonymous>)

 ---- Problem trying create css files ----

dist/styles/c-modal
dist/styles/c-navigation
dist/styles/c-table
Error: File to import not found or unreadable: ../components/forms.
    at Object.renderSync (C:\dev\sdds-1\theme\light\node_modules\node-sass\lib\index.js:440:23)
    at forEach (C:\dev\sdds-1\theme\light/gulpfile.babel.js:297:20)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds-1\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds-1\theme\light\gulpfile.babel.js:18:103)  
    at _next (C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:364 {
  status: 1,
  file: 'stdin',
  line: 4,
  column: 1,
  formatted: 'Error: File to import not found or unreadable: ../components/forms.\n' +
    '        on line 4 of stdin\n' +
    ">> @import '../components/forms';\n" +
    '\n' +
    '   ^\n'
}
Problem in file src/old/patterns/c-table.scss or imports related to it

 ---- Problem in scss files, read error! ----

TypeError: Cannot read properties of undefined (reading 'css')
    at forEach (C:\dev\sdds-1\theme\light/gulpfile.babel.js:309:49)
    at Array.forEach (<anonymous>)
    at _callee$ (C:\dev\sdds-1\theme\light/gulpfile.babel.js:174:42)
    at tryCatch (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\dev\sdds-1\theme\light\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\dev\sdds-1\theme\light\gulpfile.babel.js:18:103)  
    at _next (C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:194)
    at C:\dev\sdds-1\theme\light\gulpfile.babel.js:20:364
    at new Promise (<anonymous>)

 ---- Problem trying create css files ----

dist/styles/sdds-theme
Generate style module
Style updated.
[09:51:04] Finished 'initTheme' after 239 ms
[09:51:04] Starting 'copyScss'...
Copying scss... Output: dist/scss/
[09:51:04] Finished 'copyScss' after 95 ms
[09:51:04] Starting 'copyGlobalStyle'...
Copying corporate-ui-4 global style... output dist/styles/
[09:51:04] Finished 'copyGlobalStyle' after 6.64 ms
[09:51:04] Finished 'build' after 1.78 s
lerna info run Ran npm script 'build' in '@scania/components' in 31.2s:

> @scania/components@3.0.0 build
> npm run babel && npm run stencil --


> @scania/components@3.0.0 babel
> mkdirp .build && babel src/helpers/index.js --out-file .build/index.js        


> @scania/components@3.0.0 stencil
> stencil build --docs-json dist/data/docs.json

[51:09.2]  @stencil/core
[51:09.4]  v2.3.0
[51:09.7]  cache optimizations disabled
[51:13.1]  build, sdds-components, prod mode, started ...
[51:13.1]  transpile started ...
[51:16.5]  transpile finished in 3.42 s
[51:16.5]  copy started ...
[51:16.5]  generate custom elements bundle started ...
[51:16.5]  generate lazy started ...
[51:16.7]  copy finished (35 files) in 257 ms
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

[51:26.0]  generate custom elements bundle finished in 9.52 s
[51:35.8]  generate lazy finished in 19.32 s
[51:35.8]  updated readme docs: sdds-accordion
[51:35.8]  updated readme docs: sdds-accordion-item
[51:35.8]  updated readme docs: sdds-continousvalue-slider
[51:35.8]  updated readme docs: sdds-dropdown
[51:35.8]  updated readme docs: sdds-dropdown-filter
[51:35.8]  updated readme docs: sdds-dropdown-option
[51:35.8]  updated readme docs: sdds-dual-point-slider
[51:35.8]  updated readme docs: sdds-slider

[ WARN  ]  Package Json: package.json:10:3
           package.json "main" property is set to "dist/collection/index.js".   
           It's recommended to set the "main" property to: ./dist/index.cjs.js  

      L9:  "module": "dist/collection/index.js",
     L10:  "main": "dist/collection/index.js",
     L11:  "collection": "dist/collection/collection-manifest.json",

[ WARN  ]  Package Json: package.json:9:3
           package.json "module" property is set to "dist/collection/index.js". 
           It's recommended to set the "module" property to:
           ./dist/custom-elements/index.js

      L8:  },
      L9:  "module": "dist/collection/index.js",
     L10:  "main": "dist/collection/index.js",

[ WARN  ]  Package Json: package.json
           package.json "types" property is required when generating a
           distribution. It's recommended to set the "types" property to:       
           ./dist/types/components.d.ts

[51:36.0]  build finished in 22.91 s

lerna success run Ran npm script 'build' in 6 packages in 41.4s:
lerna success - @scania/components
lerna success - @scania/colour
lerna success - @scania/grid
lerna success - @scania/icons
lerna success - @scania/typography
lerna success - @scania/theme-light

up to date, audited 1504 packages in 1m

154 packages are looking for funding
  run `npm fund` for details

54 vulnerabilities (22 moderate, 31 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by theJohnnyMe** [comment]
Great finding @areblk , I am on removing the import of those "dead" files.

**Comment by theJohnnyMe** [comment]
I further investigated this, files are there, but it seems the issue is in the logic of adding/compling them during the build time. It needs more time to investigate but the current version seems to output success even we have some issues. I will merge one and see if it removed issues with Amplify build.

**Pull request merged**
