### PR TITLE
feat(form): added form test story

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
Adds a form test story.

**Solving issue**  
Fixes: [AB#3154](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3154)

**How to test**  
1. Go to Examples -> Form
2. Try submitting the form and check the console for logs.

## Component to add

- [x] Textfield
- [x] Textarea
- [x] Slider
- [x] Toggle
- [x] Checkbox
- [x] Radio button - added but needs some fixes
- [ ] Dropdown
- [x] Datepicker

### CODE REVIEW

**Review by theJohnnyMe — COMMENTED** [review]
I think this is a good first version, sort of testing stuff together.
What I think has to be done:

1. Maybe limit the width of the central part to ~ 300px or put it in a block component with width of ~450px. Charlotte would be best to help around. 

Another thing I noticed is that our Textarea and Textfield do not have the "required" prop, we need to add those soon.

**Comment by mJarsater** [comment]
> Member

Yes! The design I have sort of intentionally left for now, and we can check with Charlotte when all the components are merged. Nice catch on the textfield/textare, I'll add those to the backlog 🎣

**Comment by mJarsater** [comment]
> agree that it could be useful with

Yeah, I was thinking we can ask for a design from Charlotte. But I don't wanna just cram it into the sprint. I'll bring it up at planning/grooming so she can make time for it.

**Review by alexandereneroth — APPROVED** [review]
Useful as it is though. Nice work!

**Review by nathalielindqvist — COMMENTED** [review]
This might already be known, but the slider seems to default into read-only mode. Is it supposed to do that? :)
image

**Comment by mJarsater** [comment]
Will close this PR, due to it being more for testing than anything else.

**Pull request closed without merging**
