### PR TITLE
AB#804 Feature/header

### PR DESCRIPTION
**Pull request by helloimela**
**Describe pull-request**  
- Add header template from KY Header

**How to test**
- Check in storybook both mobile and desktop view
- To show side menu, switch toggle on Storybook control.

**Missing component (to be added as next feature)**
- User account styling (circle profile, and different positioning on mobile)

**Solving issue**  

Fixes: [AB#804](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/804)

### CODE REVIEW

**Review by mmexvr — APPROVED** [review]

**Comment by mmexvr** [comment]
Great work!

**Review by vichtertz — CHANGES_REQUESTED** [review]
- **Nav Menu on Medium screen:** 
Scania Symbol missing

Screenshot 2021-06-01 at 14 26 06

– The Sub-menu Icons are 20px in the documentation, not 16px (but actually in the future the icon container sizes might change anyway on the overall Scania with the release of a new icon/pictograms grids, we can quickly discuss about it if you want.)

Screenshot 2021-06-01 at 14 37 27

– The selected sub-menu item should be in bold 

Screenshot 2021-06-01 at 14 43 44

Screenshot 2021-06-01 at 14 44 40

– Same for the app launcher menu

Screenshot 2021-06-01 at 14 46 12

**Comment by helloimela** [comment]
@vichtertz I will add 20px for the icon in the menu item for now. But if it changes in the future, it can be easily changed in one place 😃 
FYI @mmexvr , I added a variable in the theme called --sdds-nav-item-icon-size: 20px

**Comment by vichtertz** [comment]
– We would like to get rid of detail-06 in SDDS typography styles, so for the category name, use headline-07 instead (Scania Sans Semi Condensed Bold, 14px/3,5rem) 
**current**:
Screenshot 2021-06-01 at 14 49 18

**with headline-07:**
Screenshot 2021-06-01 at 16 20 23

– **Global menu on small screens:**
I would keep a space on the right, like in the basic navigation, the white rectangle on the header and the white bloc of the expanded menu should be aligned

**Current:**
Screenshot 2021-06-01 at 16 28 28

**Design example**
Screenshot 2021-06-01 at 16 31 12
Screenshot 2021-06-01 at 16 32 28


– **Global menu on Medium screens**:
Should follow the same logic as Mobile, by leaving space on the right and align the white blocks

Screenshot 2021-06-01 at 16 28 46

Unless there is a specific reason to not do the same?

**Comment by vichtertz** [comment]
Only make it full screen on Mobile, keep the space on the left on Medium screen: 

Screenshot 2021-06-02 at 10 01 18

**Pull request merged**
