### PR TITLE
Improvement - Grid update 12 col + more

### PR DESCRIPTION
**Pull request by mmexvr**
**Describe pull-request**  
_Describe what the pull-request is about_

Update for the grid
- Gutter removed
- Padding value changed
- New breakpoints 
- All columns in alla breakpoints are 12
- Refactoring

Everything can be found in figma "new grid system"

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: [AB#827](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/827)

**How to test**  
_Add description how to test if possible_
1. Go to netlify / local
2. Check grid in storybook
3. Try all examples in all browsers
4. Try all breakpoints
5. Compare to figma

**Additional context**  
_Add any other context about the pull-request here._

### CODE REVIEW

**Comment by helloimela** [comment]
image

Tried in empty project without any normalize CSS. The padding added space around, need to add box-sizing:border-box manually to container, row, and cols. Should we add it by default from sdds ?

**Comment by helloimela** [comment]
On max container should be 1536px?
image
image

**Comment by mmexvr** [comment]
> image
> 
> Tried in empty project without any normalize CSS. The padding added space around (see horisontal scrollbar added), need to add box-sizing:border-box manually to container, row, and cols. Should we add it by default from sdds ?

I will have a look at it!

**Comment by mmexvr** [comment]
Added fix for the horizontal scrollbar on empty project using just grid

**Review by helloimela — APPROVED** [review]
Looks good! great job! 👍🏻

**Pull request merged**
