### PR TITLE
AB#862 Added canvas package to fix the upgrade issue to node 14 or 16

### PR DESCRIPTION
**Pull request by kjec2f**
**Describe pull-request**  
_Describe what the pull-request is about_
Added canvas package to fix the upgrade issue to node 14 or 16
Upgarded the nod-sass package to version 6.
**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #155 

**How to test**  
_Add description how to test if possible_
1. Go to...
2. Check in...
3. Run ...

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

### CODE REVIEW

**Review by helloimela — APPROVED** [review]
Great! It works fine. Only fix conflict left :) 👍🏻

**Comment by mmexvr** [comment]
I tried a clean project on node v16

- git clone
- Npm i
- npm run build

During the NPM build the initfavicon crashes

this is on mac, wonder if Windows have the same problem with a clean clone from scratch?

**Comment by kjec2f** [comment]
I have tried on a clean clone and got the same issue as well.

 I have upgraded the favicons to version 6 and it works.

So @mmexvr, Could you try the steps again on mac?

**Review by mmexvr — APPROVED** [review]

**Comment by mmexvr** [comment]
Looks good!

**Pull request merged**
