### PR TITLE
fix(tabs): Calculate tabwidth (and auto height) in componentDidRender()-method

### PR DESCRIPTION
**Pull request by albinscania**
Description says it all.

**How to test**  
Open the react project in the sandbox. Reload the page and make sure the tabs are of equal width.

### CODE REVIEW

**Comment by albinscania** [comment]
Oh! Don't forget to LINK first, to actually try it out in the react sandbox.

**Comment by mJarsater** [comment]
Might I suggest that we add a cursor:no-drop to the :hover on the disabled tabs, to correspond with the style of the disabled buttons. But we might need to check that with design first?

**Comment by albinscania** [comment]
> 

that's a great idea! will fix that on monday.

**Comment by theJohnnyMe** [comment]
@AlbinFarstun  - I think the name of PR is misleading, I guess it is about "inline-tabs".

**Comment by mJarsater** [comment]
Got the linking to work now and it looks great!

Would be nice if we could add the cursor:not-allowed on the disabled tabs and have the style not be inline. But that could be a future PR. 
Screenshot 2022-10-10 at 16 01 31

**Review by theJohnnyMe — APPROVED** [review]

**Pull request merged**
