### PR TITLE
fix(banner): close icon misplaced/shrinking when lots of text

### PR DESCRIPTION
**Pull request by alexandereneroth**
**Solving issue**  
Fixes: [AB#2605](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2605) #619

### CODE REVIEW

**Comment by mJarsater** [comment]
I think the actual 'close-icon' is too small? 

```
mask-position: center;
    mask-size: 16px;
    mask-image: url("data:image/svg+xml,%3Csvg fill='none' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M24.5 7.5a1 1 0 0 1 0 1.414L8.914 24.5A1 1 0 0 1 7.5 23.086L23.086 7.5a1 1 0 0 1 1.414 0Z' fill='currentColor'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M7.5 7.5a1 1 0 0 1 1.414 0L24.5 23.086a1 1 0 0 1-1.414 1.414L7.5 8.914a1 1 0 0 1 0-1.414Z' fill='currentColor'/%3E%3C/svg%3E ");
    mask-repeat: no-repeat;
```

Should be:
```
    mask-image: url("data:image/svg+xml,%3Csvg fill='none' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M24.5 7.5a1 1 0 0 1 0 1.414L8.914 24.5A1 1 0 0 1 7.5 23.086L23.086 7.5a1 1 0 0 1 1.414 0Z' fill='currentColor'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M7.5 7.5a1 1 0 0 1 1.414 0L24.5 23.086a1 1 0 0 1-1.414 1.414L7.5 8.914a1 1 0 0 1 0-1.414Z' fill='currentColor'/%3E%3C/svg%3E ");
    mask-position: center;
    mask-size: 20px;
    mask-repeat: no-repeat;
```

**Comment by theJohnnyMe** [comment]
> Shouldn't we use our own icon component or the webfont solution for the close button on this component? Instead of styling it in the css.
> 
> ```
>  <style>
>       @import url('https://cdn.digitaldesign.scania.com/icons/webfont/css/sdds-icons.css');
>       i {
>         font-size: 20px;
>       }
>     </style>
> <sdds-icon name="cross" size="20"> </sdds-icon>
> <i class="sdds-icon cross"></i>
> ```
> 
> EDIT: I guess this could be updated in tegel but maybe keep it the old way in scania/components?

I agree with you, lest's try to use an icon component for Tegel and keep the old one as it is.

**Comment by theJohnnyMe** [comment]
> I think the actual 'close-icon' is too small?
> 
> ```
> mask-position: center;
> mask-size: 16px;
> mask-image: url("data:image/svg+xml,%3Csvg fill='none' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M24.5 7.5a1 1 0 0 1 0 1.414L8.914 24.5A1 1 0 0 1 7.5 23.086L23.086 7.5a1 1 0 0 1 1.414 0Z' fill='currentColor'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M7.5 7.5a1 1 0 0 1 1.414 0L24.5 23.086a1 1 0 0 1-1.414 1.414L7.5 8.914a1 1 0 0 1 0-1.414Z' fill='currentColor'/%3E%3C/svg%3E ");
> mask-repeat: no-repeat;
> ```
> 
> Should be:
> 
> ```
> mask-image: url("data:image/svg+xml,%3Csvg fill='none' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M24.5 7.5a1 1 0 0 1 0 1.414L8.914 24.5A1 1 0 0 1 7.5 23.086L23.086 7.5a1 1 0 0 1 1.414 0Z' fill='currentColor'/%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M7.5 7.5a1 1 0 0 1 1.414 0L24.5 23.086a1 1 0 0 1-1.414 1.414L7.5 8.914a1 1 0 0 1 0-1.414Z' fill='currentColor'/%3E%3C/svg%3E ");
> mask-position: center;
> mask-size: 20px;
> mask-repeat: no-repeat;
> ```

I agree, I think it should be 20px too. Please double-check in Figma.

**Review by mJarsater — CHANGES_REQUESTED** [review]
See previous comments.

**Comment by alexandereneroth** [comment]
Made a breaking change for the tegel package: 
Support for just adding a `.sdds-banner-close` class was removed in favour of using the <sdds-icon> component.

Also added a button wrapper around the close button it in Storybook for accessibility.

**Review by mJarsater — APPROVED** [review]
Nice

**Review by theJohnnyMe — APPROVED** [review]
LGTM!

**Pull request merged**
