### PR TITLE
AB#476  Added textarea styling

### PR DESCRIPTION
**Pull request by helloimela**
- Extends styling from textfield

**How to test**
- Check design in Figma
- Check if textarea functions properly

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: [AB#476](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/476)

### CODE REVIEW

**Comment by mmexvr** [comment]
The focus highlight bar is not growing with the textarea when making it bigger

- Shown in chrome

**Comment by niklasros** [comment]
The icon is too dark. It should be set in $grey-300.

textarea-icon

**Comment by niklasros** [comment]
The focused line width doesn't change, when making the text area bigger. On Chrome & Safari, it's also placed a couple of pixels below the textarea when changing the size of the textarea.

_Firefox_
textarea-firefox

_Chrome & Safari_
textarea-safari

textarea-chrome

**Comment by helloimela** [comment]
Fix for focused line & resizer icon color has been added

**Comment by niklasros** [comment]
The focused line seems to be placed below the text area. On text fields, I do think it's placed inside. Sync alignment with @mmexvr so that they are consistent!

**Comment by niklasros** [comment]
The text counters default position is off. It should also follow the text area's width when changing the width.

textcounter-1

textcounter-2

**Review by niklasros — APPROVED** [review]
Looks good!

**Review by mmexvr — APPROVED** [review]

**Pull request merged**
