### PR TITLE
Tabs mode variants task 

### PR DESCRIPTION
**Pull request by EmelieLitwin**
**Describe pull-request**  
Mode variants for tabs. White background is primary and grey-50 secondary

**Solving issue**  
Fixes: [AB#3117](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3117)

### CODE REVIEW

**Review by nathalielindqvist — APPROVED** [review]
LGTM

**Comment by theJohnnyMe** [comment]
Please when merging, check that the commit message is per conventional commits standard.

**Comment by EmelieLitwin** [comment]
Make navigation primary and secondary the same and remove control

**Comment by EmelieLitwin** [comment]
@scania-digital-design-system/developers Should I make the name changes is this one or do we wait for Martins changes in the wc pr?

**Pull request merged**
