### PR TITLE
feat(header): migrate header component

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
Migration of header component.

**Solving issue**  
Fixes: [AB#2393](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2393)

**How to test**  
_Add description how to test if possible_
1. Go to storybook link below
2. Check in components -> Header
3. Check that the design is aligned with the one in Figma. 

**Screenshots**  
-

**------------------NOTE------------------**
This was quite a large job with the theme variables, so please help me test it properly.

### CODE REVIEW

**Comment by theJohnnyMe** [comment]
Please double check dividers color here and active state for third item:

Screenshot 2022-10-25 at 16 16 33

**Comment by theJohnnyMe** [comment]
Mobile menu background-colors/colors seems off: 

Screenshot 2022-10-25 at 16 16 53

**Comment by theJohnnyMe** [comment]
App launcher icon needs to be white: 

Screenshot 2022-10-25 at 16 17 06

**Comment by theJohnnyMe** [comment]
I guess this is just side-menu component is not migrated yet, but double check: 

Screenshot 2022-10-25 at 16 17 38

**Comment by theJohnnyMe** [comment]
App launcher menu seems to have grey background, take a look on bottom of the menu: 

Screenshot 2022-10-25 at 16 18 05

**Comment by mJarsater** [comment]
> There are some things that are off, but considering how big is this component - good work man ;)

Great catches! I will fix these tomorrow and then let everyone else review aswell, to make sure we aren't missing any style issues 😅

**Comment by theJohnnyMe** [comment]
A couple of visual things:

Screenshot 2022-10-31 at 10 47 27


Screenshot 2022-10-31 at 10 48 19


Screenshot 2022-10-31 at 10 48 55

**Comment by mJarsater** [comment]
@theJohnnyMe nice, thanks! I can't find a "X"-button on the current storybook either. But maybe it's missing there to? Also regarding the alignment of the search-icon. This is due to the header.css file for stories that has a `svg { vartivally-align: top; }`. Can I remove this one for now?

**Comment by mJarsater** [comment]
I have added fixes for most of the changes now. The visuall stuff regarding the grey area at the bottom of the open "launcher menu" is a tough one though. I think it's more of a visual bug related to storybook cause I cant see how this area alone would be grey. Please check it out and ping me if you find anything 😄

**Review by theJohnnyMe — APPROVED** [review]
Awesome work!

**Pull request merged**
