### PR TITLE
feat: introduction of conventional commits and lint-staged

### PR DESCRIPTION
**Pull request by theJohnnyMe**
**Describe pull-request**  
introduction of conventional commits and lint-staged

**Solving issue**  
This is an improvement for our commit log and faster code lint check

**How to test**  
1. Checkout branch
2. Run npm i to install new packages
3. Change some file scss or js/ts
4. Try to commit it following[ conventional-commits convention](https://www.conventionalcommits.org/en/v1.0.0/)
5. If it seems tricky, add files you want to commit and run "npm run commit" command to start commitizen questionare 
6. If all good with the commit message observe of liners will run on stages files.

**Additional context**  
Enable only the squash and merge option in GitHub. Talk about rebase.

### CODE REVIEW

**Comment by mmexvr** [comment]
Did a commit with the correct file rights for mac

**Comment by theJohnnyMe** [comment]
> Did a commit with the correct file rights for mac

@mmexvr  - I have tested this one on my windows, works as expected. Thanks for fix ;)

**Review by mmexvr — APPROVED** [review]
Looks good!

**Comment by theJohnnyMe** [comment]
Tested on new/fresh cloned repo, it works.

**Pull request merged**
