### PR TITLE
feat(side menu): sticky collapse button and popover example fix

### PR DESCRIPTION
**Pull request by gaonita**
**Describe pull-request**  
- placed the side menu collapse button  above the other items in the side menu and fixed on the bottom when you scroll the page
- side-menu pop-over example is fixed accordingly 

**Solving issue**  
Fixes: [AB#1164](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1164) [AB#985](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/985)
Fixes: #190 

**How to test**  

1. Go to storybook side menu example 
2. Check the sticky collapse button and pop-over example

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

### CODE REVIEW

**Comment by mmexvr** [comment]
Try and avoid including the package.json files, it is not a big thing now, but it can cause problem if we don't have our node versions and package files synced :) 

theme/light/package-lock.json

**Comment by mmexvr** [comment]
Can you add in the story, that the collapse button does the collapse part ?

**Comment by mmexvr** [comment]
Do we have an example of how the behaviour when the dropdown is open with 10+ items in the dropdown menu in figma?

 @gaonita @alexlioliopoulos

**Review by alexlioliopoulos — APPROVED** [review]
Nice, seems to work great!
Can I ask for one small thing though?
I would like us to include an arrow icon to the collapse item, like this: 
image

Let me know if that is possible, and if yes, when you can find the icon etc.

**Comment by alexlioliopoulos** [comment]
> 

I don't get it, what do you mean? Isn't it always the same, meaning that the collapse item is just placed on top of everything else? Or do I miss something?

**Comment by theJohnnyMe** [comment]
collapse_arrow_edited

See if you can align Arrow and Collapse text with Icons and Text with upper items in the menu, it is a bit off. You can easily notice Icon is not in the center when the menu is collapsed.

**Review by theJohnnyMe — APPROVED** [review]

**Comment by theJohnnyMe** [comment]
Looks OK to me.
BE AWARE:  There are valid points to refactor this but it is outside the scope of this task. A lot of CSS is written only in story file or inline which is not recommended.

**Pull request merged**
