### PR TITLE
AB#380 -  Feature/textfield options

### PR DESCRIPTION
**Pull request by mmexvr**
**Describe pull-request**  
_Describe what the pull-request is about_
Textfield component

- [x] Helper text
- [x] Error text
- [x] Error states
- [x] Disabled states
- [x] Label inside transition
- [x] Text counter
- [x] Suffix symbol
- [x] Prefix symbol
- [x] Icon Sufix
- [x] icon Prefix
- [x] Added comments for the web-component
- [x] Cleaned up the npm scripts a bit
- [x] Minor bug fixes
- [x] Focus on textfield when clicking the whole element

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #75 

**How to test**  
_Add description how to test if possible_
1. Run storybook or look at netlify
2. Check textfield options
3. Compare to figma examples

### CODE REVIEW

**Comment by niklasros** [comment]
The text fields top left and right corners should have a 4px corner radius. Currently it is 0px (Chrome, Firefox & Safari)

corners

**Comment by mmexvr** [comment]
> The text fields top left and right corners should have a 4px corner radius. Currently it is 0px (Chrome, Firefox & Safari)
> 
> corners

- Fix for Border-radius
- Temp icon size
- Grey-400 on placeholder

**Comment by niklasros** [comment]
disabled

**Comment by niklasros** [comment]
The disabled states text has the wrong colour. Should be $grey-200. I think this might have been updated by accident, when we updated the new Placeholder text colour.

disabled

**Comment by niklasros** [comment]
I can't input any text in any text fields (Safari, Chrome & Firefox).

**Comment by mmexvr** [comment]
> I can't input any text in any text fields (Safari, Chrome & Firefox).

- Added maxlength by default, that is now removed 
- Reverted the disabled color for placeholder
- Added grey-400 for default placeholder

**Review by helloimela — APPROVED** [review]
Nice!

**Review by niklasros — APPROVED** [review]

**Pull request merged**
