### PR TITLE
fix(icon): dependency on icon package

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
Updated package-lock to include dep on icon/typo/color

**Solving issue**  
Fixes: [CDEP-2709](https://tegel.atlassian.net/browse/CDEP-2709)

**How to test**  
1. Go to Storybook
2. Check in Icon
3. Make sure both component and Css Icon works.

[CDEP-2709]: https://tegel.atlassian.net/browse/CDEP-2709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alexandereneroth** [comment]
Not saying it doesn't, but how does this address the issue linked in Jira? 
Just for my own understanding.

**Comment by mJarsater** [comment]
> Not saying it doesn't, but how does this address the issue linked in Jira? Just for my own understanding.

It updates the package-lock to set the dev dependency between @scania/components and @scania/icons.

All I did to "fix" this was to do a `npm i` in the components folder.

**Review by alexandereneroth — APPROVED** [review]

**Comment by TatyanaBumazhkina** [comment]
Tested and passed.
https://deploy-preview-1059--sdds-storybook.netlify.app/?path=/story/component-icons--component page contains icon

**Comment by mJarsater** [comment]
Issue related to build config.

**Pull request closed without merging**
