### PR TITLE
perf: bump versions for a lot of packages for node v16

### PR DESCRIPTION
**Pull request by mmexvr**
**Describe pull-request**  
_Describe what the pull-request is about_

Preparation for node update [Node version LTS list](https://nodejs.org/en/about/releases/ )
- Commit that contains a lot of updates for different node packages, based on node v16 update.
- This will make it easier to run node v17 or v18(when it releases). 
- Packages that aren't update will be removed at some point and won't cause a problem
- Old components removed

**How to test**  
_Add description how to test if possible_
1. Run following commands: npm run clean, npm i, npm build, npm start, npm run link
2. Make sure everything runs, localhost
3. Linking works 
4. All the demos with linking packages
5. Make sure nothing is broken, and compare it to master 

**Additional context**  
_Add any other context about the pull-request here._
- This will add some depecrated message that we need to handle, but this will make sure reliable for node 16 and easier to upgrade to the next versions of node
- SASS requires some changes in the SASS that are being used in the grid

### CODE REVIEW

**Review by theJohnnyMe — APPROVED** [review]

**Comment by mmexvr** [comment]
@gaonita If you can test it to, that would be good

**Review by gaonita — COMMENTED** [review]
all good except EBUSY error but it resolves when I delete the dist folder. but now having a trouble to run react demo. complains about eslint 
Screenshot 2022-03-31 143633
Screenshot 2022-03-31 143700
followed this guide till number 4, but it didn't resolve the issue.  
I share this with you now to let you know the review status. 
I will proceed tomorrow, couldn't finish today due to doctor's appointment. 
I just wonder if it is only me? 🤔

**Comment by mmexvr** [comment]
@gaonita Try react now, added the package update for react demo! 👍🏼

**Review by gaonita — APPROVED** [review]
confirmed React demo works fine now :) great work!

**Comment by theJohnnyMe** [comment]
You can Squash and merge @mmexvr ;)

**Comment by mmexvr** [comment]
Done @gaonita @theJohnnyMe

**Pull request merged**
