### PR TITLE
docs: add storybook-addon-html

### PR DESCRIPTION
**Pull request by alexandereneroth**
Just tried storybook-addon-html quickly, which works better for displaying code.

However, it hydrates the components before displaying their html, which makes much code not copy-pastable.

Related to [AB#2639](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2639)

**Screenshots**  

storybook-addon-html

Screenshot 2022-11-29 at 11 10 23

### CODE REVIEW

**Comment by mJarsater** [comment]
Seems like this one had some build issues related to the spinner?

**Comment by mJarsater** [comment]
I don't know if I think this is any better than just using the docs tab like we are today?

**Review by EmelieLitwin — APPROVED** [review]
Can't remember if we made a decision on this on Wednesday but I like it :)

**Comment by alexandereneroth** [comment]
I personally don't think we should merge this, because it doesn't work well for many web-components, since it shows the hydrated HTML.

**Comment by mJarsater** [comment]
> I personally don't think we should merge this, because it doesn't work well for many web-components, since it shows the hydrated HTML. Unsure how to fix this for now.

Agree 👍

**Pull request closed without merging**
