### PR TITLE
chore(react-sandbox): responsive data table example

### PR DESCRIPTION
**Pull request by theJohnnyMe**
**Describe pull-request**  
Testing data-table component responsive feature in React sandbox

**Solving issue**  
There was a question from a user in the Development channel.

**Good to know**

- Separate page  was created to make tests for data table
- there are two different commits on how to deal with the responsiveness of data-table, please take a look on them
- this code relies on using the latest "@scania/components"

### CODE REVIEW

**Comment by mJarsater** [comment]
Could you commit the package.json also? So we get the latest @scania/components in the sandbox

**Comment by theJohnnyMe** [comment]
> Could you commit the package.json also? So we get the latest @scania/components in the sandbox

Absolutely!

**Comment by theJohnnyMe** [comment]
@mJarsater  - I did remove node_modules and run installation again. In this one, we use "latest" for all Scania packages. I can also specify 4.10.6 which is the last one released to be 100% sure, what do you think?

**Comment by mJarsater** [comment]
> @mJarsater - I did remove node_modules and run installation again. In this one, we use "latest" for all Scania packages. I can also specify 4.10.6 which is the last one released to be 100% sure, what do you think?

I would say we go with latest, that way we don't have to think about maintaining it in the future 😄

**Comment by theJohnnyMe** [comment]
> > @mJarsater - I did remove node_modules and run installation again. In this one, we use "latest" for all Scania packages. I can also specify 4.10.6 which is the last one released to be 100% sure, what do you think?
> 
> I would say we go with latest, that way we don't have to think about maintaining it in the future 😄

Then we are all good then, that one is in place already.

**Review by mJarsater — APPROVED** [review]
✅

**Pull request merged**
