### PR TITLE
AB#893 Feature/badges

### PR DESCRIPTION
**Pull request by kjec2f**
**Describe pull-request**  
_Describe what the pull-request is about_
Added Badges component implementation
**Solving issue**  

Fixes: [AB#893](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/893)

**How to test**  
_Add description how to test if possible_
1. Go to...
2. Check in...
3. Run ...

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

### CODE REVIEW

**Comment by helloimela** [comment]
I think the home component in react demo is accidentally removed? 
Please add it back.
Merge from master and fix conflict

**Comment by kjec2f** [comment]
> I think the home component in react demo is accidentally removed?
> Please add it back.
> Merge from master and fix conflict

**Review by helloimela — APPROVED** [review]

**Review by vichtertz — CHANGES_REQUESTED** [review]
Really nice work! 
I just have one feedback:
When the badge has no content, its position should still be on the top right corner of the icon:
Currently it looks like this: 
Screenshot 2021-06-29 at 11 23 42

**Comment by helloimela** [comment]
@vichtertz the positioning will be configured by the project. It is not something attached to SDDS badges. So we will merge this pull request :)

**Comment by helloimela** [comment]
We can fix the storybook example in another PR @kjec2f 
We can publish this version for now

**Comment by vichtertz** [comment]
Ah okay great :)

**Pull request merged**
