### PR TITLE
feat: (modal) Migrate modal component

### PR DESCRIPTION
**Pull request by victorscania**
**Describe pull-request**  
Migration of modal to new storybook

**Solving issue**  
[AB#2408](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2408)

**How to test**  
Open the storybook and validate the migrated in accordance with the migration-checklist

### CODE REVIEW

**Comment by theJohnnyMe** [comment]
Native one seems to miss typography styles, check if there are font variables in place

Screenshot 2022-10-20 at 15 20 43

**Comment by theJohnnyMe** [comment]
Check if colors are assigned correctly. I just tested with a black background, modal seems to be transparent: 

Screenshot 2022-10-20 at 15 22 27

**Comment by victorscania** [comment]
> Check if colors are assigned correctly. I just tested with a black background, modal seems to be transparent:
> 
> Screenshot 2022-10-20 at 15 22 27

reinstalled the repo when I had commit issues. Forgot to re-add the css to the global.css. should work now

**Comment by victorscania** [comment]
> Native one seems to miss typography styles, check if there are font variables in place
> 
> Screenshot 2022-10-20 at 15 20 43

We should look at this together, because I'm not getting these issues.

**Comment by mJarsater** [comment]
I would recommend deleting this request and starting a new one branching out of main. It's what I had to do with the popover and textfield/area ones.

**Pull request closed without merging**
