### PR TITLE
Feature - Modal component v1

### PR DESCRIPTION
**Pull request by mmexvr**
**Describe pull-request**  
_Describe what the pull-request is about_

- [x] Sizing (follow the grid column size)
- [x] Action support
- [x] Possibility to prevent click on backdrop
- [x] Overflow hidden on backdrop
- [x] Fixed position on the modal

Waiting for more info about the position for modal on pushed grid after talk with UI

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: [AB#682](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/682)

**How to test**  
_Add description how to test if possible_
- Run storybook/go to netlify on the preview link below
- Test sizing by changing the property in storybook
- Test different screensizes

### CODE REVIEW

**Comment by helloimela** [comment]
Question: Should the modal has padding / margin left - right on mobile view? Between modal box and the page

image

**Review by helloimela — CHANGES_REQUESTED** [review]
Nice! 
Only fix conflict and it looks good

**Comment by helloimela** [comment]
Note: need to think a way how the screen size mixins for rem can be exported in grid/spacing package, so it can be utilized by other app as well.

**Review by vichtertz — CHANGES_REQUESTED** [review]
**Spacing:**
- Missing 16px padding between Headline and cross icon
- From $screen-L to $screen-XXL, add 48px padding between Headline and cross icon
- From $screen-L to $screen-XXL, add 48px padding between paragraph and cross icon

**Text-style:** 
Paragraph font style should be $Body-01
- Font-size should be 4rem
- Text line height too small: should be 6rem
- Also check the letter-spacing: should be 0,02em

**Responsiveness:**
- Modal size "jump" between $screen-M and $screen-L breakpoint
- Modal-Medium, Modal-Small and Modal-XSmall become full-width when scaling down to $screen-M format: should take respectively 7/8 columns, 6/8 columns and 4/8 columns

**Comment by mmexvr** [comment]
- Fixed issue with padding on smaller screen
- Fixed typograhpy
- Padding on header/body + icon 

The jump is based on how many columns it takes, lg and mg are larger on smaller screens then it might be on bigger

**Comment by mmexvr** [comment]
> Note: need to think a way how the screen size mixins for rem can be exported in grid/spacing package, so it can be utilized by other app as well.

Added comment regarding that and will create issue. Same problem in grid system, based on the media rules

**Review by helloimela — APPROVED** [review]

**Review by vichtertz — CHANGES_REQUESTED** [review]
- Modal max-width = 1120px width (= modal-L on screen-XXL taking 12/16 columns width)

-  Modal-XS on screen-S : Margin on the sides missing

Screenshot 2021-04-19 at 11 23 47

- Double-check if Modal-XS takes 4/8 columns on screen-M (it looks like it takes more columns)
Screenshot 2021-04-19 at 11 34 00



- Modal-xs on screen-L, screen-XL, screen-XXL: text container should align to the cross on the right

Screenshot 2021-04-19 at 11 25 49

**Pull request merged**
